---1
create or replace view XEMTTNV
as
    select NV.MANV, HONV, TENNV, GIOITINH, NGAYSINH, SOBHXH, TENLOAINV, TRINHDOHV, TRINHDOCM
    from NHANVIEN NV, CHUYENMON CHM, HOCVAN HV, LOAINHANVIEN LNV
    where NV.MACM=CHM.MACM and HV.MAHV=NV.MAHV and NV.MALOAINV=LNV.MALOAINV
    with read only;

select * from XEMTTNV;

---2
CREATE OR REPLACE VIEW XEMPBCUANV
AS
   SELECT NV.MANV, TENNV, PB.MAPHONG, TENPHONG
    FROM NHANVIEN NV, PHONGBAN PB
    WHERE NV.MAPHONG = PB.MAPHONG
    WITH READ ONLY;
    SELECT * FROM XEMPBCUANV;

---3
create or replace view XEMSLNVCUAPHONG
 as   
    select TENPHONG, COUNT(MANV) as SOLUONGNV
    from NHANVIEN NV full join PHONGBAN PB on PB.MAPHONG=NV.MAPHONG
    group by TENPHONG
    with read only;

select * from XEMSLNVCUAPHONG;


---4

CREATE OR REPLACE VIEW XEMNGAYHD
AS
    SELECT NV.MANV, TENNV,HD.MAHD,NGAYKY
    FROM HOPDONG HD, NHANVIEN NV
    WHERE HD.MANV = NV.MANV
    WITH READ ONLY;

SELECT * FROM  XEMNGAYHD;

---5

create or replace view XEMNGAYNGHIDILAM
as
    select NV.MANV, TENNV, TKCC.THANGTK, NAMTK, SONGAYNGHI, SONGAYDILAM
    from THONGKECHAMCONG TKCC, NHANVIEN NV
    where NV.MANV=TKCC.MANV
    with read only;
    
--6.
CREATE OR REPLACE VIEW XEMTTTP
AS 
    SELECT PB.TRUONGPHONG, NV.TENNV, GIOITINH, NGAYSINH, SOBHXH, PB.TENPHONG, CHM.TRINHDOCM, HV.TRINHDOHV
    FROM PHONGBAN PB , NHANVIEN NV, HOCVAN HV, CHUYENMON CHM
    WHERE PB.TRUONGPHONG = NV.MANV AND HV.MAHV = NV.MAHV AND CHM.MACM = NV.MACM
    WITH READ ONLY;
    
SELECT * FROM  XEMTTTP;

--7 xem ch?c v? c?a t?ng ng??i và h?p ??ng h? còn gia h?n CH và coi b?ng h? s? l??ng c?a h?
CREATE OR REPLACE VIEW  XEMCVHSL
AS
    SELECT NV.MANV, TENNV, CV.TENCV, HD.NGAYKY, TRANGTHAI, HSL.BAC, NHOMNGACH, HESOLUONG
    FROM CHUCVU CV, NHANVIEN NV , HOPDONG HD, BANGHESOLUONG HSL
    WHERE CV.MACV = NV.MACV  AND HD.MANV = NV.MANV AND HSL.MAHESOLUONG = NV.MAHESOLUONG
    WITH READ ONLY;
SELECT * FROM  XEMCVHSL;

--8

create or replace view XEMNGHIKPCP
as    
    select NV.MANV, TENNV, TKCC.THANGTK, NAMTK, NGHICP, NGHIKP, NGHIBHXH
    from THONGKECHAMCONG TKCC, NHANVIEN NV
    where NV.MANV=TKCC.MANV
    with read only;

---9

create or replace view HSLTP
as
    select TENPHONG, HONV, TENNV, HESOLUONG
    from BANGHESOLUONG HSL, PHONGBAN PB, NHANVIEN NV
    where HSL.MAHESOLUONG=NV.MAHESOLUONG and NV.MANV=PB.TRUONGPHONG
    with read only;
    
---10.xem NV nào ngh? nhi?u nh?t 
CREATE OR REPLACE VIEW XEMNVNGHINN
AS 
    SELECT NV.MANV, TENNV, SUM(TKCC.SONGAYNGHI) as SONGAYNGHI, NAMTK
    FROM NHANVIEN NV, THONGKECHAMCONG TKCC
    WHERE  NV.MANV = TKCC.MANV
    GROUP BY NV.MANV, TENNV, NAMTK
    HAVING SUM(TKCC.SONGAYNGHI)>=(
                                                                SELECT MAX(SUM(TKCC.SONGAYNGHI))
                                                                FROM NHANVIEN NV, THONGKECHAMCONG TKCC
                                                                WHERE  NV.MANV = TKCC.MANV
                                                                GROUP BY NV.MANV, TENNV, NAMTK
    )
    WITH CHECK OPTION;
    
    select * from XEMNVNGHINN;

--11

create or replace view XEMLHDNV
as
    select NV.MANV, NV.TENNV, HD.MAHD, LHD.MALHD, LHD.LOAIHD
    from HOPDONG HD, LOAIHD LHD, NHANVIEN NV
    where HD.MALHD=LHD.MALHD and NV.MANV=HD.MANV
    with read only;
    